<!doctype html>
<html>
<head>
    <title>OpenLayers Editor</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="favicon.ico" type="image/vnd.microsoft.icon">
    <link rel="stylesheet" href="<?php echo ROOT_DIR ?>js/ole/theme/geosilk/geosilk.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo ROOT_DIR ?>js/openlayers/theme/default/style.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo ROOT_DIR ?>css/style.css" type="text/css" />
</head>
<body>
    <a href="http://github.com/geops/ole">
    <img id="github" src="<?php echo ROOT_DIR ?>img/github-ribbon.png" alt="Fork me on GitHub">
    </a>
    <div id="page">
        <ul id="navigation">
            <li><a href="#map">Map</a></li>
            <li><a href="#video">Video</a></li>
            <li><a href="#features">Features</a></li>
            <li><a href="#documentation">Documentation</a></li>
        </ul>
        <h1>OpenLayers Editor</h1>
        <div id="map" class="content"></div>
        <div id="features" class="content">
            <?php echo $this->action('features', 'index'); ?>
        </div>
        <div id="documentation" class="content">
            <?php echo $this->action('documentation', 'index'); ?>
        </div>
        <div id="video" class="content">
            <iframe style="margin-left: 80px;" width="640" height="480" src="http://www.youtube-nocookie.com/embed/eJQIN7j2r9o?hd=1" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
    <div id="credit">developed by <a href="http://www.geops.de"><img src="<?php echo ROOT_DIR ?>img/geops.png" alt="geOps"></a></div>
</body>

<?php if (ini_get("display_errors")) : ?>
    <script src="<?php echo ROOT_DIR ?>js/openlayers/lib/OpenLayers.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/openlayers/lib/OpenLayers/Lang/en.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/ole/lib/Editor/Lang/en.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/ole/lib/loader.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/jquery.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/demo.js"></script>
<?php else : ?>
    <script src="<?php echo ROOT_DIR ?>js/min/openlayers.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/min/ole.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/min/jquery.js"></script>
<?php endif; ?>
    <script>
        OpenLayers.ImgPath = '<?php echo ROOT_DIR ?>img/openlayers/';
        $(function() {
            $('#map').data('editor').oleUrl = '<?php echo ROOT_DIR ?>ole/';
        });
    </script>
</html>
