<!doctype html>
<html>
<head>
    <title>OpenLayers Editor: Spatial Data Editing for Web GIS</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="favicon.ico" type="image/vnd.microsoft.icon">
    <link rel="stylesheet" href="<?php echo ROOT_DIR ?>js/ole/theme/geosilk/geosilk.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo ROOT_DIR ?>js/openlayers/theme/default/style.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo ROOT_DIR ?>css/style.css" type="text/css" />
    <script type="text/javascript" src="<?php echo ROOT_DIR ?>js/iefixes.js"></script>
    <meta name="robots" content="index,follow,noodp,noydir" />
    <meta name="keywords" content="Spatial Web, Web GIS, Geodata Editing, Spatial Data Editing, OpenLayers Editor" />
    <meta name="author" content="geOps Spatial Web" />
    <meta name="page-topic" content="Geodata Editing, Spatial Data Editing" />
    <meta name="description" content="Full-featured customizable editor for spatial data. Demo with assisted drawing and spatial operations." />
</head>
<body>
    <a href="http://github.com/geops/ole">
    <img id="github" src="<?php echo ROOT_DIR ?>img/github-ribbon.png" alt="Fork me on GitHub">
    </a>
    <div id="page">
        <ul id="navigation">
            <li><a href="#map">Demo Map</a></li>
            <li><a href="#video">Video</a></li>
            <li><a href="#features">Features</a></li>
            <li><a href="#documentation">Documentation</a></li>
        </ul>
        <h1>OpenLayers Editor</h1>
        <div id="map" class="content"></div>
        <div id="features" class="content" style="height:auto">
            <?php echo $this->action('features', 'index'); ?>
        </div>
        <div id="documentation" class="content">
            <?php echo $this->action('documentation', 'index'); ?>
        </div>
        <div id="video" class="content">
            <iframe style="margin-left: 80px;" width="640" height="480" src="http://www.youtube-nocookie.com/embed/eJQIN7j2r9o?hd=1" frameborder="0" allowfullscreen></iframe>
        </div>
        <p style="margin-bottom:0px; margin-left:0px;">
            <a title="Share this on Twitter" class="share-button" target="share" href="https://twitter.com/share?url=http%3A%2F%2Fole.geops.de%2F&amp;text=%23OpenLayers%20Editor%20for%20sophisticated%20%23geospatial%20edits%20in%20web%20%23GIS">
                <img alt="Tweet" src="<?php echo ROOT_DIR ?>img/share-icons/twitter.png"></a>
            <a title="Share this on Facebook" class="share-button" target="share" href="http://www.facebook.com/sharer.php?u=http%3A%2F%2Fole.geops.de%2F&amp;t=%23OpenLayers%20Editor%20for%20sophisticated%20%23geospatial%20edits%20in%20web%20%23GIS">
                <img alt="Share on Facebook" src="<?php echo ROOT_DIR ?>img/share-icons/facebook.png"></a>
        </p>
        <div id="credit" title="Spatial Web and GIS Integration into Business Processes">developed by <a href="http://www.geops.de"><img src="<?php echo ROOT_DIR ?>img/geops.png" alt="geOps Open Source Spatial Web"></a></div>
    </div>

<?php if (ini_get("display_errors")) : ?>
    <script src="<?php echo ROOT_DIR ?>js/openlayers/lib/OpenLayers.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/openlayers/lib/OpenLayers/Lang/en.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/ole/lib/Editor/Lang/en.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/ole/lib/loader.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/jquery.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/demo.js"></script>
<?php else : ?>
    <script src="<?php echo ROOT_DIR ?>js/min/openlayers.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/min/ole.js"></script>
    <script src="<?php echo ROOT_DIR ?>js/min/jquery.js"></script>
<?php endif; ?>
    <script type="text/javascript">
        OpenLayers.ImgPath = '<?php echo ROOT_DIR ?>img/openlayers/';
        $(function() {
            $('#map').data('editor').oleUrl = '<?php echo ROOT_DIR ?>ole/';
        });
    </script>
    </body>
</html>
