<?php

class IndexController extends Zend_Controller_Action
{

    public function indexAction()
    {
    }

    public function featuresAction()
    {
        // HTML file views/scripts/index/features.phtml
        // generated by Makefile from GitHub repository
    }

    public function documentationAction()
    {
        // HTML file views/scripts/index/documentation.phtml
        // generated by Makefile from GitHub repository
    }

}

